//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS__provider_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccesToMenuItems
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int ItemId { get; set; }
    
        public virtual MenuItems MenuItems { get; set; }
        public virtual RolesEmployees RolesEmployees { get; set; }
    }
}
