//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS__provider_.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_TNSEntities : DbContext
    {
        public DB_TNSEntities()
            : base("name=DB_TNSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccesToMenuItems> AccesToMenuItems { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equips> Equips { get; set; }
        public virtual DbSet<Genders> Genders { get; set; }
        public virtual DbSet<MenuItems> MenuItems { get; set; }
        public virtual DbSet<ReasonsForTermination> ReasonsForTermination { get; set; }
        public virtual DbSet<RolesEmployees> RolesEmployees { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<ServicesInContract> ServicesInContract { get; set; }
        public virtual DbSet<Subscribers> Subscribers { get; set; }
        public virtual DbSet<TypesContract> TypesContract { get; set; }
    }
}
