//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS__provider_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contracts()
        {
            this.ServicesInContract = new HashSet<ServicesInContract>();
            this.Subscribers = new HashSet<Subscribers>();
        }
    
        public int Id { get; set; }
        public string ContractNumber { get; set; }
        public int IdSubscriber { get; set; }
        public System.DateTime DateOfCinclusion { get; set; }
        public int TypeContractId { get; set; }
        public int PersonalAccount { get; set; }
        public int ConnectedEquipId { get; set; }
        public Nullable<int> ReasonForTerminationID { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public string Description { get; set; }
    
        public virtual Equips Equips { get; set; }
        public virtual ReasonsForTermination ReasonsForTermination { get; set; }
        public virtual TypesContract TypesContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesInContract> ServicesInContract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Subscribers> Subscribers { get; set; }
    }
}
