//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS__provider_.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServicesInContract
    {
        public int Id { get; set; }
        public string ContractNumberId { get; set; }
        public int TypeServicesId { get; set; }
    
        public virtual Contracts Contracts { get; set; }
        public virtual Services Services { get; set; }
    }
}
