//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNS__provider_
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DbTnsEntities : DbContext
    {
        //для подключения бд
        private static DbTnsEntities _context;
        public DbTnsEntities()
            : base("name=DbTnsEntities")
        {
        }

        /// <summary>
        /// Для создания подключения к бд.
        /// </summary>
        /// <returns>Контекст БД.</returns>
        public static DbTnsEntities GetContext()
        {
            if (_context == null)
            {
                _context = new DbTnsEntities();
            }
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<RolesEmployees> RolesEmployees { get; set; }
    }
}
